language: php
dist: trusty
sudo: false

php: 7.0

jobs:
  include:
    - stage: lint
      install: composer install
      script: composer lint
    - language: node
      node: 9.3
      install: yarn
      script: yarn run lint

cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $TRAVIS_BUILD_DIR/node_modules
    - $HOME/.composer/cache
