version: '3.0'
services:
  web:
    image: alexcheng/magento2:2.2.4-developer
    ports:
      - 80:80
    links:
      - db
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/app/code/DigitalHub/Ebanx

  db:
    image: mysql:5.6.23
    ports:
      - ${MYSQL_EXTERNAL_PORT:-3306}:3306
    volumes:
      - ./.db-data:/var/lib/mysql/data
    env_file:
      - .env
volumes:
  db-data:
